### ISSUE TITLE
add local network backup support. 

### ISSUE THREAD

**Issue by fotoklaasje** [uroni/urbackup-client-docker#1]
I use urbackup for local network backups, server and client run in separate dockers on the same machine. At the moment the dockerfile for this docker contains `CMD ["--internet-only"]`, forcing the client into internet mode. This causes unnecessary network traffic to the router and back, congesting my ethernet connection and slowing the backups. i would greatly appreciate it if this flag could be removed or replaced by an environment variable, which I can change.

**Comment by jejanim** [comment]
I'd appreciate that change too.
The hard-coded, enabled internet mode prevents me from using this image.

**Comment by knumsi** [comment]
I cannot get it up and running. QNAP TVS-672XT Container Station shows the following log:
`2020-09-09 22:49:29: ERROR: urbackupserver: Failed binding ipv6 socket to port 35623. Another instance of this application may alrea
be active and bound to this port.                                                                                                   
2020-09-09 22:49:29: urbackupserver: Server started up successfully!                                                                
2020-09-09 22:49:29: Started UrBackupClient Backend...                                                                              
Backing up volume /backup                                                                                                           
2020-09-09 22:49:30: Looking for old Sessions... 2 sessions                                                                         
2020-09-09 22:49:30: Final path: /backup                                                                                            
2020-09-09 22:49:39: Final path: /backup  `

**Config is:**
`version: '3'

services:
  urbackup:
    image: uroni/urbackup-client:latest
    container_name: urbackup-client
    environment:
      - TZ=Europe/Berlin # Enter your timezone
      - URBACKUP_SERVER_NAME=XYZ (Local Lan Name or Internet Name dont change anything)
      - URBACKUP_CLIENT_NAME=XXX (Like shown in the status overview)
      - URBACKUP_CLIENT_AUTHKEY=XYZABC (as set up in 
    volumes:
      - /share/CACHEDEV1_DATA:/backup:ro
    ports:
      - 35621:35621
      - 35622:35622
      - 35623:35623`

Removing the three ports in the config did not solve anything. Both Devices are on the local network.

**Comment by knumsi** [comment]
Okay - workaround for me after long searching around:
Router ist opnsense: 
Add in "Services: Unbound DNS: Overrides" the external host to point at the internal Urbackup IP.

Now it works. with my before mentioned YAML.

**Comment by laurentlemercier** [comment]
> I use urbackup for local network backups, server and client run in separate dockers on the same machine. At the moment the dockerfile for this docker contains `CMD ["--internet-only"]`, forcing the client into internet mode. This causes unnecessary network traffic to the router and back, congesting my ethernet connection and slowing the backups. i would greatly appreciate it if this flag could be removed or replaced by an environment variable, which I can change.

you can change it by using in docker compose : 
    command: []

but watch out with network considerations with docker...

**Comment by knumsi** [comment]
Awesome, thank you very much!!!

Works like a charm =)

**Comment by laurentlemercier** [comment]
Can you share your stack ? I wanted to know how you deal with ports...

**Comment by knumsi** [comment]
Sure, here my working yaml:

```
version: '2'

services:
  urbackup:
    image: uroni/urbackup-server:latest
    container_name: urbackup
    restart: unless-stopped # | no | always | on-failure # v2 compose
    command: [] # Allows LAN and Internet Mode 
    environment:
      - PUID=1000 # Enter the UID of the user who should own the files here
      - PGID=1000  # Enter the GID of the user who should own the files here
      - TZ=Europe/Berlin # Enter your timezone
    volumes:
      - ??????????????????/container-urbackup-server/database:/var/urbackup
      - ??????????????????/container-urbackup-server/backups:/backups
      - ??????????????????/container-urbackup-server/var/log:/var/log
      # Uncomment the next line if you want to bind-mount the www-folder
      #- /path/to/wwwfolder:/usr/share/urbackup
    network_mode: "host"
    ports:
      # The Server binds to following default ports: 
      - 55413:55413/tcp # FastCGI for web interface 
      - 55414:55414/tcp # HTTP web interface 
      - 55415:55415/tcp # Internet clients --> Only Port for all Internet traffic
      - 35623:35623/udp # UDP broadcasts for discovery - OUTGOING
      # The Client binds to following default ports (all incoming):
      #- 35621:35621/tcp
      #- 35622:35622/udp
    # Activate the following two lines for BTRFS support
    #cap_add:
    #  - SYS_ADMIN
```
